# Site settings
title: Geeky Pixel
email: arturo@arturoalviar.com
description: GeekyPixel is a blog to showcase DailyUI designs made by Arturo Alviar.
url: "http://geekypixel.design" # the base hostname & protocol for your site
twitter_username: elguey77
github_username:  arturoalviar

# Build settings
markdown: kramdown
permalink: /:title

#Front matter defaults

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: Arturo Alviar
      layout: "post"
